FROM maven:3.8.6-openjdk-8

WORKDIR /app

RUN apt-get update && \
    apt-get install -y autoconf automake libtool curl wget make g++ unzip python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y xmlstarlet && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install beautifulsoup4 lxml

RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz && \
    tar -xzf protobuf-2.5.0.tar.gz && \
    cd protobuf-2.5.0 && \
    ./configure && make && make install && ldconfig && \
    cd .. && rm -rf protobuf-2.5.0 protobuf-2.5.0.tar.gz

ENV MAVEN_OPTS="-Dmaven.repo.local=/root/.m2/repository"

ENV MODULE=""
ENV DIR_TO_PYTHON_SCRIPT=""
ENV FULL_TEST_NAME=""
ENV ITERATIONS="5"

CMD ["/bin/bash", "-c", "cd /app/source && chmod +x statistics_generator.sh && ./statistics_generator.sh \"$MODULE\" \"$DIR_TO_PYTHON_SCRIPT\" \"$FULL_TEST_NAME\" \"$ITERATIONS\""]
