FROM maven:3.8.6-openjdk-11

WORKDIR /app

RUN apt-get update && \
    apt-get install -y autoconf automake libtool curl make g++ unzip python3 python3-pip git && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y xmlstarlet && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install beautifulsoup4 lxml

RUN git clone https://github.com/TestingResearchIllinois/maven-surefire.git /app/maven-surefire

RUN cd /app/maven-surefire && \
    mvn install -DskipTests -Drat.skip -Denforcer.skip

RUN mkdir -p /usr/share/maven/lib/ext && \
    cp /app/maven-surefire/surefire-changing-maven-extension/target/surefire-changing-maven-extension-1.0-SNAPSHOT.jar /usr/share/maven/lib/ext/

RUN rm -rf /app/maven-surefire && apt-get autoremove -y && apt-get clean

ENV MAVEN_OPTS="-Dmaven.repo.local=/root/.m2/repository"

ENV MODULE=""
ENV DIR_TO_PYTHON_SCRIPT=""
ENV FULL_TEST_NAME=""
ENV ITERATIONS="5"
