#maven plugin help mojo generation informations
#Thu Jun 26 10:25:35 EDT 2025
helpPackageName=
destinationDirectory=/home/srafi/idflakies_nio/iDFlakies/idflakies-maven-plugin/target/generated-sources/plugin
